name: ci

on:
  push:
  pull_request:

jobs:
  check-codespaces:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
      env:
        CODESPACES: true
    steps:
      - uses: actions/checkout@v2
      - run: sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply ostrowr
      - name: chezmoi data
        run: ./bin/chezmoi data

  check-debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply ostrowr
      - name: chezmoi data
        run: ./bin/chezmoi data

  check-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply ostrowr
      - name: chezmoi data
        run: ./bin/chezmoi data
